// Bilingual UI copy. English (USA) and Spanish (México) — accessed via useCopy()
// with a dot-path key, e.g. t('hero.ctaPrimary'). Spanish is warm, polished
// Mexico Spanish using "tú". Branch-specific brand/contact prose (hero kicker,
// taglines, addresses) lives in location.jsx, since a branch always maps to one
// language.

export const COPY = {
  en: {
    nav: {
      home: "HOME",
      services: "SERVICES",
      beautyBar: "REFRESHMENTS", // USA menu (no alcohol); MX keeps "BEAUTY BAR"
      book: "BOOK APPOINTMENT",
      contact: "CONTACT",
      bookCta: "Book Appointment",
      switchToOther: "Switch to USA", // shown to MX users (destination language)
      backToTop: "Back to top",
    },
    notFound: {
      script: "Lost Among The Daisies",
      title: "PAGE NOT FOUND",
      body: "The page you're looking for has drifted away. Let's take you back to the beauty.",
      cta: "BACK TO HOME",
    },
    hero: {
      title1: "An Elevated",
      title2: "Beauty Bar",
      ctaPrimary: "Book Now",
      ctaSecondary: "Explore Services",
    },
    indulgence: {
      kicker: "More Than A Salon",
      title1: "Where Beauty",
      title2: "Meets Indulgence",
      body1: "Margaret's Beauty Bar combines premium beauty services with an upscale social atmosphere.",
      body2: "Enjoy signature refreshments while receiving world-class treatments in a space designed for you.",
    },
    features: {
      luxuryTitle: "LUXURIOUS\nEXPERIENCE",
      luxuryText: "Premium services in an\nelegant environment.",
      socialTitle: "REFRESHMENTS\n& SOCIAL",
      socialText: "Signature refreshments and\na vibrant atmosphere.",
      productsTitle: "PREMIUM\nPRODUCTS",
      productsText: "High-quality products for\nbeautiful, long-lasting results.",
      artistsTitle: "EXPERT\nARTISTS",
      artistsText: "Highly trained professionals\nwho care about you.",
    },
    signature: {
      title: "Our Signature Services",
      viewAll: "VIEW ALL",
      subtitle: "Carefully Curated Treatments To Relax, Rejuvenate, And Renew.",
      kidsName: "Kids' Nail Polish",
      facialsName: "Facials",
      manicureName: "Manicure",
      cardSub: "Revitalize And Nourish\nYour Skin",
    },
    servicesPage: {
      heroTitle: "BEAUTY. LUXURY. YOU.",
      heroScript: "Services We Offer",
      heroBody: "Indulge In Premium Beauty Services Designed To Make You Look And Feel Your Best.",
      ourServices: "OUR",
      services: "SERVICES",
      nailTitle: "Nail Art",
      nailTagline: "Turn your imagination into nail art. From custom designs to your favorite images, we can create it all on your nails. Visit us today!",
      nailBody: "At Margaret's Beauty Bar, we offer everything your nails deserve—from classic nail polish to sophisticated acrylic and gel enhancements. Explore an extensive palette of colors, stunning decorations, and the latest innovations in nail care, featuring the newest trends and premium products available on the market, including:",
      lashesTitle: "Eyelashes",
      lashesIntro: "Elevate your look with our precision lash services – from soft, natural volume to bold, glamorous styles, every set is crafted to perfection.",
      lashNatural: "Natural Look",
      lashNaturalText: "Get a natural look with this technique, and show off longer, fuller, and curlier lashes.",
      lashHybrid: "Hybrid Look",
      lashHybridText: "It's an intermediate application between the natural look and the volume look.",
      lashVolume: "Look Volume",
      lashVolumeText: "Dare to rock a more intense look with our volume lashes. Come and get 3 times more volume.",
      lashLift: "Lashlift",
      lashLiftText: "The Lashlift technique is not a lash curl; it's a root lift and tint application that gives you greater volume. We stretch and separate your lashes one by one, achieving a natural lift, a fuller curl, and a more intense color. The results last up to two months, regardless of your daily activities.",
      hairTitle1: "Straightened, Wavy Or Casual Express",
      hairText1: "Don't Let Anything Stop You, Give Us A Few Minutes To Make Your Hair Beautiful And Ready For That Business Meeting, Lunch With Friends, Or Dinner With That Special Someone.",
      hairTitle2: "Hairstyles For Events",
      hairText2: "Your Hairstyle Should Be The Star Of The Event; Having A Bad Hairstyle Is Something We Can't Afford. Leave That Special Day In Our Hands.",
      hairScript: "Hairstyles",
      spaFoot: "Foot Spa",
      spaFootText: "Your Feet Are Your Support, And Our Foot Baths Know It. They Are Designed To Provide You With HYDROTHERAPY And CHRONOTHERAPY, Treatments That Will Guarantee An Improvement In Your Mood, Physical And Mental Relaxation, And A Reduction In Daily Stress And Anxiety.",
      spaThreading: "Threading",
      spaThreadingText: "Threading Provides Extra Cleansing And Allows For The Removal Of Even The Shortest Or Ingrown Hairs. As It Is A Non-Invasive Technique, It Is Suitable For Acne-Prone Skin.",
      spaWaxing: "Waxing",
      spaWaxingText: "For Our Waxing Service, We Use The Best Waxes, Made From Specially Optimized Polymers, To Give You The Best Hair Removal Experience. Their Chemical Composition Prevents The Wax From Sticking To The Skin, Focusing Solely On Hair Removal And Minimizing Any Discomfort.",
      makeupTitle: "Makeup",
      makeupSocial: "Social Makeup",
      makeupSocialText: "We'll Bring Out The Best In You With Day Or Night Makeup. Whether It's For Work, Dinner, An Event, Or New Year's Eve.",
      makeupBridal: "Bridal Makeup",
      makeupBridalText: "At Margaret's Beauty Bar We Avoid Conventional Wedding Practices; To Highlight The Natural Beauty Of Each Bride We Carry Out A Detailed Preliminary Study Of Her Characteristics And Personal Tastes.",
    },
    book: {
      script: "Reserve Your Moment",
      title: "BOOK AN APPOINTMENT",
      intro: "Choose from {n}+ treatments across {c} categories. Tap the services you'd love, then send us your enquiry — it's that simple.",
      search: "Search a treatment… e.g. gel manicure",
      noMatch: "No treatments match “{q}” — try another word.",
      bannerText: "Prefer to book instantly?",
      bannerLink: "Reserve online →",
      selectedOne: "treatment selected",
      selectedMany: "treatments selected",
      clear: "CLEAR",
      continue: "CONTINUE TO ENQUIRY",
    },
    contact: {
      script: "Get In Touch",
      title: "CONTACT US",
      subtitle: "Whether you're booking your next indulgence or simply saying hello, we'd love to hear from you. Reach out and let's create something beautiful.",
      visitScript: "Visit Our Beauty Bar",
      visitBody: "Step into a space where premium beauty meets an upscale social atmosphere. Our doors — and our bar — are always open to you.",
      followUs: "Follow Us",
      infoVisit: "Visit Us",
      infoCall: "Call Us",
      infoEmail: "Email Us",
      infoHours: "Opening Hours",
      formScript: "Send Us A Message",
      selectionLabel: "YOUR SELECTION",
      treatmentOne: "TREATMENT",
      treatmentMany: "TREATMENTS",
      name: "YOUR NAME",
      namePh: "Jane Doe",
      phone: "PHONE",
      phonePh: "(555) 000-0000",
      email: "EMAIL",
      emailPh: "jane@email.com",
      message: "MESSAGE",
      messagePh: "Tell us how we can pamper you…",
      submit: "SEND MESSAGE",
      sending: "SENDING…",
      errName: "Please enter your name.",
      errEmail: "Please enter a valid email.",
      successTitle: "Thank You!",
      successBody: "Your message is on its way. Our team will be in touch with you very soon to help plan your visit.",
      successBookText: "For instant booking anytime,",
      successBookLink: "reserve online →",
      closeScript: "We Can't Wait",
      closeTitle: "To Welcome You To The Bar",
      callToBook: "CALL TO BOOK",
      bookingMsgIntro: "Hello! I'd like to book the following treatments:",
    },
    barMenu: {
      // USA has a no-alcohol "Refreshments" menu (see servesAlcohol in
      // location.jsx). The beer item is only rendered where alcohol is served.
      title: "Refreshments",
      subtitle: "A Perfect Blend Of Taste, Crafted For Every Mood.",
      items: {
        beer: { title: "BEER BAR", tagline: "Cold. Classic.", desc: "A Wide Selection Of Beers For Every Craft-Beer Lover." },
        coffee: { title: "COFFEE BAR", tagline: "Brewed To Perfection.", desc: "From Espresso To Cappuccino, Savor Every Sip." },
        tea: { title: "TEA BAR", tagline: "Warm. Soothing. Comforting.", desc: "A Curated Selection Of Premium Teas From Around The World." },
        soft: { title: "SOFT DRINKS", tagline: "Fresh & Refreshing.", desc: "A Variety Of Soft Drinks To Keep You Refreshed." },
        water: { title: "WATER & MORE...", tagline: "Stay Hydrated.", desc: "Still Water, Sparkling Water, And More Options." },
      },
    },
    footer: {
      quickLinks: "EXPLORE",
      ourServices: "OUR SERVICES",
      visitUs: "VISIT US",
      stayInTouch: "STAY IN TOUCH",
      newsletterText: "Join our list for seasonal offers, new treatments, and members-only events.",
      emailPh: "Your email address",
      subscribed: "You're on the list — thank you!",
      bookCta: "BOOK APPOINTMENT",
      rights: "All rights reserved.",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      lHome: "Home",
      lServices: "Services",
      lBarMenu: "Refreshments", // USA; MX keeps "Bar Menu"
      lBook: "Book Appointment",
      lContact: "Contact",
      sNail: "Nail Art",
      sLashes: "Eyelashes",
      sHair: "Hairstyles",
      sSpa: "Spa & Waxing",
      sMakeup: "Makeup",
    },
  },

  es: {
    nav: {
      home: "INICIO",
      services: "SERVICIOS",
      beautyBar: "BEAUTY BAR",
      book: "RESERVAR CITA",
      contact: "CONTACTO",
      bookCta: "Reservar Cita",
      switchToOther: "Cambiar a México", // shown to US users (destination language)
      backToTop: "Volver arriba",
    },
    notFound: {
      script: "Perdida Entre Las Margaritas",
      title: "PÁGINA NO ENCONTRADA",
      body: "La página que buscas ya no está aquí. Volvamos a la belleza.",
      cta: "VOLVER AL INICIO",
    },
    hero: {
      title1: "Un Exclusivo",
      title2: "Bar De Belleza",
      ctaPrimary: "Reservar Ahora",
      ctaSecondary: "Explorar Servicios",
    },
    indulgence: {
      kicker: "Más Que Un Salón",
      title1: "Donde la Belleza",
      title2: "Se Vuelve Placer",
      body1: "Margaret's Beauty Bar combina servicios de belleza premium con un ambiente social de alto nivel.",
      body2: "Disfruta cócteles de autor mientras recibes tratamientos de clase mundial en un espacio diseñado para ti.",
    },
    features: {
      luxuryTitle: "EXPERIENCIA\nDE LUJO",
      luxuryText: "Servicios premium en un\nambiente elegante.",
      socialTitle: "CÓCTELES\n& CONVIVENCIA",
      socialText: "Cócteles de autor y\nun ambiente vibrante.",
      productsTitle: "PRODUCTOS\nPREMIUM",
      productsText: "Productos de alta calidad para\nresultados hermosos y duraderos.",
      artistsTitle: "ARTISTAS\nEXPERTAS",
      artistsText: "Profesionales altamente capacitadas\nque se preocupan por ti.",
    },
    signature: {
      title: "Nuestros Servicios Exclusivos",
      viewAll: "VER TODO",
      subtitle: "Tratamientos Cuidadosamente Seleccionados Para Relajar, Rejuvenecer Y Renovar.",
      kidsName: "Esmaltado Para Niñas",
      facialsName: "Faciales",
      manicureName: "Manicura",
      cardSub: "Revitaliza Y Nutre\nTu Piel",
    },
    servicesPage: {
      heroTitle: "BELLEZA. LUJO. TÚ.",
      heroScript: "Servicios Que Ofrecemos",
      heroBody: "Consiéntete Con Servicios De Belleza Premium Diseñados Para Que Te Veas Y Te Sientas De Maravilla.",
      ourServices: "NUESTROS",
      services: "SERVICIOS",
      nailTitle: "Arte en Uñas",
      nailTagline: "Convierte tu imaginación en arte en uñas. Desde diseños personalizados hasta tus imágenes favoritas, lo creamos todo en tus uñas. ¡Visítanos hoy!",
      nailBody: "En Margaret's Beauty Bar ofrecemos todo lo que tus uñas merecen: desde el esmalte clásico hasta sofisticadas aplicaciones de acrílico y gel. Explora una amplia paleta de colores, decoraciones espectaculares y las últimas innovaciones en el cuidado de uñas, con las tendencias más nuevas y productos premium disponibles en el mercado, incluyendo:",
      lashesTitle: "Pestañas",
      lashesIntro: "Realza tu mirada con nuestros servicios de pestañas de precisión: desde un volumen suave y natural hasta estilos audaces y glamorosos, cada set se crea a la perfección.",
      lashNatural: "Look Natural",
      lashNaturalText: "Consigue un look natural con esta técnica y presume pestañas más largas, tupidas y rizadas.",
      lashHybrid: "Look Híbrido",
      lashHybridText: "Es una aplicación intermedia entre el look natural y el look de volumen.",
      lashVolume: "Look Volumen",
      lashVolumeText: "Atrévete a lucir una mirada más intensa con nuestras pestañas de volumen. Ven y obtén 3 veces más volumen.",
      lashLift: "Lifting de Pestañas",
      lashLiftText: "La técnica de Lifting no es un rizado común; es una elevación desde la raíz con aplicación de tinte que te da mayor volumen. Estiramos y separamos tus pestañas una por una, logrando una elevación natural, un rizo más marcado y un color más intenso. Los resultados duran hasta dos meses, sin importar tus actividades diarias.",
      hairTitle1: "Lacio, Ondulado O Express Casual",
      hairText1: "No Dejes Que Nada Te Detenga; Danos Unos Minutos Para Dejar Tu Cabello Hermoso Y Listo Para Esa Junta De Trabajo, Comida Con Amigas O Cena Con Esa Persona Especial.",
      hairTitle2: "Peinados Para Eventos",
      hairText2: "Tu Peinado Debe Ser La Estrella Del Evento; Un Mal Peinado Es Algo Que No Podemos Permitir. Deja Ese Día Especial En Nuestras Manos.",
      hairScript: "Peinados",
      spaFoot: "Spa de Pies",
      spaFootText: "Tus Pies Son Tu Soporte, Y Nuestros Baños Para Pies Lo Saben. Están Diseñados Para Brindarte HIDROTERAPIA Y CROMOTERAPIA, Tratamientos Que Garantizan Una Mejora En Tu Estado De Ánimo, Relajación Física Y Mental, Y Una Reducción Del Estrés Y La Ansiedad Diaria.",
      spaThreading: "Hilo",
      spaThreadingText: "La Depilación Con Hilo Ofrece Una Limpieza Extra Y Permite Retirar Incluso Los Vellos Más Cortos O Enterrados. Al Ser Una Técnica No Invasiva, Es Ideal Para Piel Con Tendencia Al Acné.",
      spaWaxing: "Depilación con Cera",
      spaWaxingText: "Para Nuestro Servicio De Depilación Usamos Las Mejores Ceras, Hechas Con Polímeros Especialmente Optimizados, Para Darte La Mejor Experiencia. Su Composición Evita Que La Cera Se Adhiera A La Piel, Enfocándose Solo En El Vello Y Minimizando Cualquier Molestia.",
      makeupTitle: "Maquillaje",
      makeupSocial: "Maquillaje Social",
      makeupSocialText: "Sacaremos Lo Mejor De Ti Con Maquillaje De Día O De Noche. Ya Sea Para El Trabajo, Una Cena, Un Evento O Fin De Año.",
      makeupBridal: "Maquillaje de Novia",
      makeupBridalText: "En Margaret's Beauty Bar Evitamos Las Prácticas Convencionales De Boda; Para Resaltar La Belleza Natural De Cada Novia Realizamos Un Estudio Preliminar Detallado De Sus Características Y Gustos Personales.",
    },
    book: {
      script: "Reserva Tu Momento",
      title: "RESERVA TU CITA",
      intro: "Elige entre más de {n} tratamientos en {c} categorías. Toca los servicios que te encanten y envíanos tu consulta — así de sencillo.",
      search: "Busca un tratamiento… ej. manicura en gel",
      noMatch: "Ningún tratamiento coincide con “{q}” — intenta con otra palabra.",
      bannerText: "¿Prefieres reservar al instante?",
      bannerLink: "Reserva en línea →",
      selectedOne: "tratamiento seleccionado",
      selectedMany: "tratamientos seleccionados",
      clear: "LIMPIAR",
      continue: "CONTINUAR CON LA CONSULTA",
    },
    contact: {
      script: "Contáctanos",
      title: "CONTÁCTANOS",
      subtitle: "Ya sea que quieras reservar tu próxima consentida o simplemente saludar, nos encantaría saber de ti. Escríbenos y creemos algo hermoso juntas.",
      visitScript: "Visita Nuestro Beauty Bar",
      visitBody: "Entra a un espacio donde la belleza premium se encuentra con un ambiente social de alto nivel. Nuestras puertas — y nuestro bar — siempre están abiertas para ti.",
      followUs: "Síguenos",
      infoVisit: "Visítanos",
      infoCall: "Llámanos",
      infoEmail: "Escríbenos",
      infoHours: "Horario",
      formScript: "Envíanos un Mensaje",
      selectionLabel: "TU SELECCIÓN",
      treatmentOne: "TRATAMIENTO",
      treatmentMany: "TRATAMIENTOS",
      name: "TU NOMBRE",
      namePh: "María López",
      phone: "TELÉFONO",
      phonePh: "(55) 0000 0000",
      email: "CORREO",
      emailPh: "maria@correo.com",
      message: "MENSAJE",
      messagePh: "Cuéntanos cómo podemos consentirte…",
      submit: "ENVIAR MENSAJE",
      sending: "ENVIANDO…",
      errName: "Por favor ingresa tu nombre.",
      errEmail: "Por favor ingresa un correo válido.",
      successTitle: "¡Gracias!",
      successBody: "Tu mensaje va en camino. Nuestro equipo se pondrá en contacto contigo muy pronto para ayudarte a planear tu visita.",
      successBookText: "Para reservar al instante cuando quieras,",
      successBookLink: "reserva en línea →",
      closeScript: "Te Esperamos",
      closeTitle: "Para Darte La Bienvenida Al Bar",
      callToBook: "LLAMAR PARA RESERVAR",
      bookingMsgIntro: "¡Hola! Me gustaría reservar los siguientes tratamientos:",
    },
    barMenu: {
      title: "Bar Menu",
      subtitle: "La Combinación Perfecta De Sabor, Creada Para Cada Momento.",
      items: {
        beer: { title: "BAR DE CERVEZA", tagline: "Fría, Clásica.", desc: "Una Amplia Variedad De Cervezas Para Todo Amante De La Buena Cerveza." },
        coffee: { title: "BAR DE CAFÉ", tagline: "Preparado A La Perfección.", desc: "Del Espresso Al Capuchino, Disfruta Cada Sorbo." },
        tea: { title: "BAR DE TÉ", tagline: "Cálido. Relajante. Reconfortante.", desc: "Una Selección De Tés Premium De Todo El Mundo." },
        soft: { title: "REFRESCOS", tagline: "Frescos Y Refrescantes.", desc: "Una Variedad De Refrescos Para Mantenerte Hidratado." },
        water: { title: "AGUA Y MUCHO MÁS...", tagline: "Mantente Hidratado.", desc: "Agua Natural, Agua Mineral Y Más Opciones." },
      },
    },
    footer: {
      quickLinks: "EXPLORAR",
      ourServices: "NUESTROS SERVICIOS",
      visitUs: "VISÍTANOS",
      stayInTouch: "MANTENTE EN CONTACTO",
      newsletterText: "Únete a nuestra lista para ofertas de temporada, nuevos tratamientos y eventos exclusivos.",
      emailPh: "Tu correo electrónico",
      subscribed: "¡Ya estás en la lista — gracias!",
      bookCta: "RESERVAR CITA",
      rights: "Todos los derechos reservados.",
      privacy: "Aviso de Privacidad",
      terms: "Términos del Servicio",
      lHome: "Inicio",
      lServices: "Servicios",
      lBarMenu: "Bar Menu",
      lBook: "Reservar Cita",
      lContact: "Contacto",
      sNail: "Arte en Uñas",
      sLashes: "Pestañas",
      sHair: "Peinados",
      sSpa: "Spa y Depilación",
      sMakeup: "Maquillaje",
    },
  },
};
